# es配置
elasticsearch:
  rest:
    clusterName: my_cluster
    clusterNodes: 49.232.226.131  #多个节点地址，用逗号分隔
    clusterPorts: 9200
    connection-timeout: 8000     # 可选，连接超时时间（毫秒）
    read-timeout: 60000          # 可选，读取超时时间（毫秒）
#management:
#  health:
#    elasticsearch:
#      enabled: true
#      uris: http://49.232.226.131:9200
#      period: 30s

