// source: proto/MyMessage.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var proto_User_pb = require('../proto/User_pb.js');
goog.object.extend(proto, proto_User_pb);
var proto_Game_pb = require('../proto/Game_pb.js');
goog.object.extend(proto, proto_Game_pb);
goog.exportSymbol('proto.com.zgame.proto.MyMessage', null, global);
goog.exportSymbol('proto.com.zgame.proto.MyMessage.TypeCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.zgame.proto.MyMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.zgame.proto.MyMessage.oneofGroups_);
};
goog.inherits(proto.com.zgame.proto.MyMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.zgame.proto.MyMessage.displayName = 'proto.com.zgame.proto.MyMessage';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.zgame.proto.MyMessage.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.com.zgame.proto.MyMessage.TypeCase = {
  TYPE_NOT_SET: 0,
  USERMSG: 2,
  GAMEMSG: 3
};

/**
 * @return {proto.com.zgame.proto.MyMessage.TypeCase}
 */
proto.com.zgame.proto.MyMessage.prototype.getTypeCase = function() {
  return /** @type {proto.com.zgame.proto.MyMessage.TypeCase} */(jspb.Message.computeOneofCase(this, proto.com.zgame.proto.MyMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.zgame.proto.MyMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.com.zgame.proto.MyMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.zgame.proto.MyMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.zgame.proto.MyMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    usermsg: (f = msg.getUsermsg()) && proto_User_pb.UserMsg.toObject(includeInstance, f),
    gamemsg: (f = msg.getGamemsg()) && proto_Game_pb.GameMsg.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.zgame.proto.MyMessage}
 */
proto.com.zgame.proto.MyMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.zgame.proto.MyMessage;
  return proto.com.zgame.proto.MyMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.zgame.proto.MyMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.zgame.proto.MyMessage}
 */
proto.com.zgame.proto.MyMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = new proto_User_pb.UserMsg;
      reader.readMessage(value,proto_User_pb.UserMsg.deserializeBinaryFromReader);
      msg.setUsermsg(value);
      break;
    case 3:
      var value = new proto_Game_pb.GameMsg;
      reader.readMessage(value,proto_Game_pb.GameMsg.deserializeBinaryFromReader);
      msg.setGamemsg(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.zgame.proto.MyMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.zgame.proto.MyMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.zgame.proto.MyMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.zgame.proto.MyMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getUsermsg();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_User_pb.UserMsg.serializeBinaryToWriter
    );
  }
  f = message.getGamemsg();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto_Game_pb.GameMsg.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.com.zgame.proto.MyMessage.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.zgame.proto.MyMessage} returns this
 */
proto.com.zgame.proto.MyMessage.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional UserMsg userMsg = 2;
 * @return {?proto.com.zgame.proto.UserMsg}
 */
proto.com.zgame.proto.MyMessage.prototype.getUsermsg = function() {
  return /** @type{?proto.com.zgame.proto.UserMsg} */ (
    jspb.Message.getWrapperField(this, proto_User_pb.UserMsg, 2));
};


/**
 * @param {?proto.com.zgame.proto.UserMsg|undefined} value
 * @return {!proto.com.zgame.proto.MyMessage} returns this
*/
proto.com.zgame.proto.MyMessage.prototype.setUsermsg = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.com.zgame.proto.MyMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.zgame.proto.MyMessage} returns this
 */
proto.com.zgame.proto.MyMessage.prototype.clearUsermsg = function() {
  return this.setUsermsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.zgame.proto.MyMessage.prototype.hasUsermsg = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional GameMsg gameMsg = 3;
 * @return {?proto.com.zgame.proto.GameMsg}
 */
proto.com.zgame.proto.MyMessage.prototype.getGamemsg = function() {
  return /** @type{?proto.com.zgame.proto.GameMsg} */ (
    jspb.Message.getWrapperField(this, proto_Game_pb.GameMsg, 3));
};


/**
 * @param {?proto.com.zgame.proto.GameMsg|undefined} value
 * @return {!proto.com.zgame.proto.MyMessage} returns this
*/
proto.com.zgame.proto.MyMessage.prototype.setGamemsg = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.com.zgame.proto.MyMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.zgame.proto.MyMessage} returns this
 */
proto.com.zgame.proto.MyMessage.prototype.clearGamemsg = function() {
  return this.setGamemsg(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.zgame.proto.MyMessage.prototype.hasGamemsg = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.com.zgame.proto);
