// source: proto/User.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var proto_common_user_pb = require('../proto/common_user_pb.js');
goog.object.extend(proto, proto_common_user_pb);
goog.exportSymbol('proto.com.zgame.proto.UserMsg', null, global);
goog.exportSymbol('proto.com.zgame.proto.UserMsg.TypeCase', null, global);
goog.exportSymbol('proto.com.zgame.proto.User_Req_10001', null, global);
goog.exportSymbol('proto.com.zgame.proto.User_Res_10002', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.zgame.proto.UserMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.zgame.proto.UserMsg.oneofGroups_);
};
goog.inherits(proto.com.zgame.proto.UserMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.zgame.proto.UserMsg.displayName = 'proto.com.zgame.proto.UserMsg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.zgame.proto.User_Req_10001 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.zgame.proto.User_Req_10001, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.zgame.proto.User_Req_10001.displayName = 'proto.com.zgame.proto.User_Req_10001';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.zgame.proto.User_Res_10002 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.zgame.proto.User_Res_10002, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.zgame.proto.User_Res_10002.displayName = 'proto.com.zgame.proto.User_Res_10002';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.zgame.proto.UserMsg.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.com.zgame.proto.UserMsg.TypeCase = {
  TYPE_NOT_SET: 0,
  REQ10001: 2,
  RES10002: 3
};

/**
 * @return {proto.com.zgame.proto.UserMsg.TypeCase}
 */
proto.com.zgame.proto.UserMsg.prototype.getTypeCase = function() {
  return /** @type {proto.com.zgame.proto.UserMsg.TypeCase} */(jspb.Message.computeOneofCase(this, proto.com.zgame.proto.UserMsg.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.zgame.proto.UserMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.com.zgame.proto.UserMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.zgame.proto.UserMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.zgame.proto.UserMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    uid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    req10001: (f = msg.getReq10001()) && proto.com.zgame.proto.User_Req_10001.toObject(includeInstance, f),
    res10002: (f = msg.getRes10002()) && proto.com.zgame.proto.User_Res_10002.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.zgame.proto.UserMsg}
 */
proto.com.zgame.proto.UserMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.zgame.proto.UserMsg;
  return proto.com.zgame.proto.UserMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.zgame.proto.UserMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.zgame.proto.UserMsg}
 */
proto.com.zgame.proto.UserMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUid(value);
      break;
    case 2:
      var value = new proto.com.zgame.proto.User_Req_10001;
      reader.readMessage(value,proto.com.zgame.proto.User_Req_10001.deserializeBinaryFromReader);
      msg.setReq10001(value);
      break;
    case 3:
      var value = new proto.com.zgame.proto.User_Res_10002;
      reader.readMessage(value,proto.com.zgame.proto.User_Res_10002.deserializeBinaryFromReader);
      msg.setRes10002(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.zgame.proto.UserMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.zgame.proto.UserMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.zgame.proto.UserMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.zgame.proto.UserMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getReq10001();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.zgame.proto.User_Req_10001.serializeBinaryToWriter
    );
  }
  f = message.getRes10002();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.zgame.proto.User_Res_10002.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 uid = 1;
 * @return {number}
 */
proto.com.zgame.proto.UserMsg.prototype.getUid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.zgame.proto.UserMsg} returns this
 */
proto.com.zgame.proto.UserMsg.prototype.setUid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional User_Req_10001 req10001 = 2;
 * @return {?proto.com.zgame.proto.User_Req_10001}
 */
proto.com.zgame.proto.UserMsg.prototype.getReq10001 = function() {
  return /** @type{?proto.com.zgame.proto.User_Req_10001} */ (
    jspb.Message.getWrapperField(this, proto.com.zgame.proto.User_Req_10001, 2));
};


/**
 * @param {?proto.com.zgame.proto.User_Req_10001|undefined} value
 * @return {!proto.com.zgame.proto.UserMsg} returns this
*/
proto.com.zgame.proto.UserMsg.prototype.setReq10001 = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.com.zgame.proto.UserMsg.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.zgame.proto.UserMsg} returns this
 */
proto.com.zgame.proto.UserMsg.prototype.clearReq10001 = function() {
  return this.setReq10001(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.zgame.proto.UserMsg.prototype.hasReq10001 = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional User_Res_10002 res10002 = 3;
 * @return {?proto.com.zgame.proto.User_Res_10002}
 */
proto.com.zgame.proto.UserMsg.prototype.getRes10002 = function() {
  return /** @type{?proto.com.zgame.proto.User_Res_10002} */ (
    jspb.Message.getWrapperField(this, proto.com.zgame.proto.User_Res_10002, 3));
};


/**
 * @param {?proto.com.zgame.proto.User_Res_10002|undefined} value
 * @return {!proto.com.zgame.proto.UserMsg} returns this
*/
proto.com.zgame.proto.UserMsg.prototype.setRes10002 = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.com.zgame.proto.UserMsg.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.zgame.proto.UserMsg} returns this
 */
proto.com.zgame.proto.UserMsg.prototype.clearRes10002 = function() {
  return this.setRes10002(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.zgame.proto.UserMsg.prototype.hasRes10002 = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.zgame.proto.User_Req_10001.prototype.toObject = function(opt_includeInstance) {
  return proto.com.zgame.proto.User_Req_10001.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.zgame.proto.User_Req_10001} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.zgame.proto.User_Req_10001.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    msgdata: (f = msg.getMsgdata()) && proto_common_user_pb.UserData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.zgame.proto.User_Req_10001}
 */
proto.com.zgame.proto.User_Req_10001.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.zgame.proto.User_Req_10001;
  return proto.com.zgame.proto.User_Req_10001.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.zgame.proto.User_Req_10001} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.zgame.proto.User_Req_10001}
 */
proto.com.zgame.proto.User_Req_10001.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMsgid(value);
      break;
    case 2:
      var value = new proto_common_user_pb.UserData;
      reader.readMessage(value,proto_common_user_pb.UserData.deserializeBinaryFromReader);
      msg.setMsgdata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.zgame.proto.User_Req_10001.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.zgame.proto.User_Req_10001.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.zgame.proto.User_Req_10001} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.zgame.proto.User_Req_10001.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMsgid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMsgdata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_common_user_pb.UserData.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 msgId = 1;
 * @return {number}
 */
proto.com.zgame.proto.User_Req_10001.prototype.getMsgid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.zgame.proto.User_Req_10001} returns this
 */
proto.com.zgame.proto.User_Req_10001.prototype.setMsgid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional UserData msgData = 2;
 * @return {?proto.com.zgame.proto.UserData}
 */
proto.com.zgame.proto.User_Req_10001.prototype.getMsgdata = function() {
  return /** @type{?proto.com.zgame.proto.UserData} */ (
    jspb.Message.getWrapperField(this, proto_common_user_pb.UserData, 2));
};


/**
 * @param {?proto.com.zgame.proto.UserData|undefined} value
 * @return {!proto.com.zgame.proto.User_Req_10001} returns this
*/
proto.com.zgame.proto.User_Req_10001.prototype.setMsgdata = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.zgame.proto.User_Req_10001} returns this
 */
proto.com.zgame.proto.User_Req_10001.prototype.clearMsgdata = function() {
  return this.setMsgdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.zgame.proto.User_Req_10001.prototype.hasMsgdata = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.zgame.proto.User_Res_10002.prototype.toObject = function(opt_includeInstance) {
  return proto.com.zgame.proto.User_Res_10002.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.zgame.proto.User_Res_10002} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.zgame.proto.User_Res_10002.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    msgdata: (f = msg.getMsgdata()) && proto_common_user_pb.UserData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.zgame.proto.User_Res_10002}
 */
proto.com.zgame.proto.User_Res_10002.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.zgame.proto.User_Res_10002;
  return proto.com.zgame.proto.User_Res_10002.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.zgame.proto.User_Res_10002} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.zgame.proto.User_Res_10002}
 */
proto.com.zgame.proto.User_Res_10002.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMsgid(value);
      break;
    case 2:
      var value = new proto_common_user_pb.UserData;
      reader.readMessage(value,proto_common_user_pb.UserData.deserializeBinaryFromReader);
      msg.setMsgdata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.zgame.proto.User_Res_10002.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.zgame.proto.User_Res_10002.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.zgame.proto.User_Res_10002} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.zgame.proto.User_Res_10002.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMsgid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMsgdata();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto_common_user_pb.UserData.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 msgId = 1;
 * @return {number}
 */
proto.com.zgame.proto.User_Res_10002.prototype.getMsgid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.zgame.proto.User_Res_10002} returns this
 */
proto.com.zgame.proto.User_Res_10002.prototype.setMsgid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional UserData msgData = 2;
 * @return {?proto.com.zgame.proto.UserData}
 */
proto.com.zgame.proto.User_Res_10002.prototype.getMsgdata = function() {
  return /** @type{?proto.com.zgame.proto.UserData} */ (
    jspb.Message.getWrapperField(this, proto_common_user_pb.UserData, 2));
};


/**
 * @param {?proto.com.zgame.proto.UserData|undefined} value
 * @return {!proto.com.zgame.proto.User_Res_10002} returns this
*/
proto.com.zgame.proto.User_Res_10002.prototype.setMsgdata = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.zgame.proto.User_Res_10002} returns this
 */
proto.com.zgame.proto.User_Res_10002.prototype.clearMsgdata = function() {
  return this.setMsgdata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.zgame.proto.User_Res_10002.prototype.hasMsgdata = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.com.zgame.proto);
