// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common_game.proto

package com.z.model.proto;

public final class CommonGame {
  private CommonGame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.z.model.proto.CardSuit}
   */
  public enum CardSuit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *黑桃
     * </pre>
     *
     * <code>Spades = 0;</code>
     */
    Spades(0),
    /**
     * <pre>
     *红桃
     * </pre>
     *
     * <code>Hearts = 1;</code>
     */
    Hearts(1),
    /**
     * <pre>
     *方片
     * </pre>
     *
     * <code>Diamonds = 2;</code>
     */
    Diamonds(2),
    /**
     * <pre>
     *梅花
     * </pre>
     *
     * <code>Clubs = 3;</code>
     */
    Clubs(3),
    /**
     * <pre>
     *大王
     * </pre>
     *
     * <code>BigJoker = 100;</code>
     */
    BigJoker(100),
    /**
     * <pre>
     *小王
     * </pre>
     *
     * <code>SmallJoker = 200;</code>
     */
    SmallJoker(200),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *黑桃
     * </pre>
     *
     * <code>Spades = 0;</code>
     */
    public static final int Spades_VALUE = 0;
    /**
     * <pre>
     *红桃
     * </pre>
     *
     * <code>Hearts = 1;</code>
     */
    public static final int Hearts_VALUE = 1;
    /**
     * <pre>
     *方片
     * </pre>
     *
     * <code>Diamonds = 2;</code>
     */
    public static final int Diamonds_VALUE = 2;
    /**
     * <pre>
     *梅花
     * </pre>
     *
     * <code>Clubs = 3;</code>
     */
    public static final int Clubs_VALUE = 3;
    /**
     * <pre>
     *大王
     * </pre>
     *
     * <code>BigJoker = 100;</code>
     */
    public static final int BigJoker_VALUE = 100;
    /**
     * <pre>
     *小王
     * </pre>
     *
     * <code>SmallJoker = 200;</code>
     */
    public static final int SmallJoker_VALUE = 200;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CardSuit valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CardSuit forNumber(int value) {
      switch (value) {
        case 0: return Spades;
        case 1: return Hearts;
        case 2: return Diamonds;
        case 3: return Clubs;
        case 100: return BigJoker;
        case 200: return SmallJoker;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CardSuit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CardSuit> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CardSuit>() {
            public CardSuit findValueByNumber(int number) {
              return CardSuit.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommonGame.getDescriptor().getEnumTypes().get(0);
    }

    private static final CardSuit[] VALUES = values();

    public static CardSuit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CardSuit(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.CardSuit)
  }

  public interface CardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.z.model.proto.Card)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>.com.z.model.proto.CardSuit suit = 2;</code>
     * @return The enum numeric value on the wire for suit.
     */
    int getSuitValue();
    /**
     * <code>.com.z.model.proto.CardSuit suit = 2;</code>
     * @return The suit.
     */
    CardSuit getSuit();
  }
  /**
   * <pre>
   * 卡牌数据
   * </pre>
   *
   * Protobuf type {@code com.z.model.proto.Card}
   */
  public static final class Card extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.z.model.proto.Card)
      CardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Card.newBuilder() to construct.
    private Card(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Card() {
      suit_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Card();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonGame.internal_static_com_z_model_proto_Card_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonGame.internal_static_com_z_model_proto_Card_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Card.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int SUIT_FIELD_NUMBER = 2;
    private int suit_;
    /**
     * <code>.com.z.model.proto.CardSuit suit = 2;</code>
     * @return The enum numeric value on the wire for suit.
     */
    @Override public int getSuitValue() {
      return suit_;
    }
    /**
     * <code>.com.z.model.proto.CardSuit suit = 2;</code>
     * @return The suit.
     */
    @Override public CardSuit getSuit() {
      @SuppressWarnings("deprecation")
      CardSuit result = CardSuit.valueOf(suit_);
      return result == null ? CardSuit.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (suit_ != CardSuit.Spades.getNumber()) {
        output.writeEnum(2, suit_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (suit_ != CardSuit.Spades.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, suit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Card)) {
        return super.equals(obj);
      }
      Card other = (Card) obj;

      if (getId()
          != other.getId()) return false;
      if (suit_ != other.suit_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + SUIT_FIELD_NUMBER;
      hash = (53 * hash) + suit_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Card parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Card parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Card parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Card parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Card parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Card parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Card parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Card parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Card parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Card parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Card parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Card parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Card prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 卡牌数据
     * </pre>
     *
     * Protobuf type {@code com.z.model.proto.Card}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.z.model.proto.Card)
        CardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonGame.internal_static_com_z_model_proto_Card_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonGame.internal_static_com_z_model_proto_Card_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Card.class, Builder.class);
      }

      // Construct using com.z.model.proto.CommonGame.Card.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        suit_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonGame.internal_static_com_z_model_proto_Card_descriptor;
      }

      @Override
      public Card getDefaultInstanceForType() {
        return Card.getDefaultInstance();
      }

      @Override
      public Card build() {
        Card result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Card buildPartial() {
        Card result = new Card(this);
        result.id_ = id_;
        result.suit_ = suit_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Card) {
          return mergeFrom((Card)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Card other) {
        if (other == Card.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.suit_ != 0) {
          setSuitValue(other.getSuitValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                suit_ = input.readEnum();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int suit_ = 0;
      /**
       * <code>.com.z.model.proto.CardSuit suit = 2;</code>
       * @return The enum numeric value on the wire for suit.
       */
      @Override public int getSuitValue() {
        return suit_;
      }
      /**
       * <code>.com.z.model.proto.CardSuit suit = 2;</code>
       * @param value The enum numeric value on the wire for suit to set.
       * @return This builder for chaining.
       */
      public Builder setSuitValue(int value) {
        
        suit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.z.model.proto.CardSuit suit = 2;</code>
       * @return The suit.
       */
      @Override
      public CardSuit getSuit() {
        @SuppressWarnings("deprecation")
        CardSuit result = CardSuit.valueOf(suit_);
        return result == null ? CardSuit.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.z.model.proto.CardSuit suit = 2;</code>
       * @param value The suit to set.
       * @return This builder for chaining.
       */
      public Builder setSuit(CardSuit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        suit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.z.model.proto.CardSuit suit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuit() {
        
        suit_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.z.model.proto.Card)
    }

    // @@protoc_insertion_point(class_scope:com.z.model.proto.Card)
    private static final Card DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Card();
    }

    public static Card getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Card>
        PARSER = new com.google.protobuf.AbstractParser<Card>() {
      @Override
      public Card parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Card> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Card> getParserForType() {
      return PARSER;
    }

    @Override
    public Card getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MahjongDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.z.model.proto.MahjongData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>int64 num = 2;</code>
     * @return The num.
     */
    long getNum();

    /**
     * <code>int64 radio = 3;</code>
     * @return The radio.
     */
    long getRadio();

    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   * 麻将数据
   * </pre>
   *
   * Protobuf type {@code com.z.model.proto.MahjongData}
   */
  public static final class MahjongData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.z.model.proto.MahjongData)
      MahjongDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MahjongData.newBuilder() to construct.
    private MahjongData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MahjongData() {
      name_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MahjongData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonGame.internal_static_com_z_model_proto_MahjongData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonGame.internal_static_com_z_model_proto_MahjongData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MahjongData.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int NUM_FIELD_NUMBER = 2;
    private long num_;
    /**
     * <code>int64 num = 2;</code>
     * @return The num.
     */
    @Override
    public long getNum() {
      return num_;
    }

    public static final int RADIO_FIELD_NUMBER = 3;
    private long radio_;
    /**
     * <code>int64 radio = 3;</code>
     * @return The radio.
     */
    @Override
    public long getRadio() {
      return radio_;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile Object name_;
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (num_ != 0L) {
        output.writeInt64(2, num_);
      }
      if (radio_ != 0L) {
        output.writeInt64(3, radio_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (num_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, num_);
      }
      if (radio_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, radio_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MahjongData)) {
        return super.equals(obj);
      }
      MahjongData other = (MahjongData) obj;

      if (getId()
          != other.getId()) return false;
      if (getNum()
          != other.getNum()) return false;
      if (getRadio()
          != other.getRadio()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNum());
      hash = (37 * hash) + RADIO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRadio());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MahjongData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MahjongData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MahjongData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MahjongData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MahjongData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MahjongData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MahjongData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MahjongData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MahjongData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MahjongData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MahjongData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MahjongData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MahjongData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 麻将数据
     * </pre>
     *
     * Protobuf type {@code com.z.model.proto.MahjongData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.z.model.proto.MahjongData)
        MahjongDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonGame.internal_static_com_z_model_proto_MahjongData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonGame.internal_static_com_z_model_proto_MahjongData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MahjongData.class, Builder.class);
      }

      // Construct using com.z.model.proto.CommonGame.MahjongData.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        num_ = 0L;

        radio_ = 0L;

        name_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonGame.internal_static_com_z_model_proto_MahjongData_descriptor;
      }

      @Override
      public MahjongData getDefaultInstanceForType() {
        return MahjongData.getDefaultInstance();
      }

      @Override
      public MahjongData build() {
        MahjongData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MahjongData buildPartial() {
        MahjongData result = new MahjongData(this);
        result.id_ = id_;
        result.num_ = num_;
        result.radio_ = radio_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MahjongData) {
          return mergeFrom((MahjongData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MahjongData other) {
        if (other == MahjongData.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getNum() != 0L) {
          setNum(other.getNum());
        }
        if (other.getRadio() != 0L) {
          setRadio(other.getRadio());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();

                break;
              } // case 8
              case 16: {
                num_ = input.readInt64();

                break;
              } // case 16
              case 24: {
                radio_ = input.readInt64();

                break;
              } // case 24
              case 34: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private long num_ ;
      /**
       * <code>int64 num = 2;</code>
       * @return The num.
       */
      @Override
      public long getNum() {
        return num_;
      }
      /**
       * <code>int64 num = 2;</code>
       * @param value The num to set.
       * @return This builder for chaining.
       */
      public Builder setNum(long value) {
        
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNum() {
        
        num_ = 0L;
        onChanged();
        return this;
      }

      private long radio_ ;
      /**
       * <code>int64 radio = 3;</code>
       * @return The radio.
       */
      @Override
      public long getRadio() {
        return radio_;
      }
      /**
       * <code>int64 radio = 3;</code>
       * @param value The radio to set.
       * @return This builder for chaining.
       */
      public Builder setRadio(long value) {
        
        radio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 radio = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRadio() {
        
        radio_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 4;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.z.model.proto.MahjongData)
    }

    // @@protoc_insertion_point(class_scope:com.z.model.proto.MahjongData)
    private static final MahjongData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MahjongData();
    }

    public static MahjongData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MahjongData>
        PARSER = new com.google.protobuf.AbstractParser<MahjongData>() {
      @Override
      public MahjongData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MahjongData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MahjongData> getParserForType() {
      return PARSER;
    }

    @Override
    public MahjongData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_z_model_proto_Card_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_z_model_proto_Card_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_z_model_proto_MahjongData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_z_model_proto_MahjongData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021common_game.proto\022\021com.z.model.proto\"=" +
      "\n\004Card\022\n\n\002id\030\001 \001(\003\022)\n\004suit\030\002 \001(\0162\033.com.z" +
      ".model.proto.CardSuit\"C\n\013MahjongData\022\n\n\002" +
      "id\030\001 \001(\003\022\013\n\003num\030\002 \001(\003\022\r\n\005radio\030\003 \001(\003\022\014\n\004" +
      "name\030\004 \001(\t*Z\n\010CardSuit\022\n\n\006Spades\020\000\022\n\n\006He" +
      "arts\020\001\022\014\n\010Diamonds\020\002\022\t\n\005Clubs\020\003\022\014\n\010BigJo" +
      "ker\020d\022\017\n\nSmallJoker\020\310\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_z_model_proto_Card_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_z_model_proto_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_z_model_proto_Card_descriptor,
        new String[] { "Id", "Suit", });
    internal_static_com_z_model_proto_MahjongData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_z_model_proto_MahjongData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_z_model_proto_MahjongData_descriptor,
        new String[] { "Id", "Num", "Radio", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
