// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common_user.proto

package com.z.model.proto;

public final class CommonUser {
  private CommonUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   *用户类型
   * </pre>
   *
   * Protobuf enum {@code com.z.model.proto.UserType}
   */
  public enum UserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *普通用户
     * </pre>
     *
     * <code>COMMON = 0;</code>
     */
    COMMON(0),
    /**
     * <pre>
     * 一级代理（每条线的总控）
     * </pre>
     *
     * <code>LINE_MANAGER = 1;</code>
     */
    LINE_MANAGER(1),
    /**
     * <pre>
     * 二级代理
     * </pre>
     *
     * <code>LINE_VIP1 = 2;</code>
     */
    LINE_VIP1(2),
    /**
     * <pre>
     * 三级代理
     * </pre>
     *
     * <code>LINE_VIP2 = 3;</code>
     */
    LINE_VIP2(3),
    /**
     * <pre>
     *总控
     * </pre>
     *
     * <code>MANAGER = 10000;</code>
     */
    MANAGER(10000),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *普通用户
     * </pre>
     *
     * <code>COMMON = 0;</code>
     */
    public static final int COMMON_VALUE = 0;
    /**
     * <pre>
     * 一级代理（每条线的总控）
     * </pre>
     *
     * <code>LINE_MANAGER = 1;</code>
     */
    public static final int LINE_MANAGER_VALUE = 1;
    /**
     * <pre>
     * 二级代理
     * </pre>
     *
     * <code>LINE_VIP1 = 2;</code>
     */
    public static final int LINE_VIP1_VALUE = 2;
    /**
     * <pre>
     * 三级代理
     * </pre>
     *
     * <code>LINE_VIP2 = 3;</code>
     */
    public static final int LINE_VIP2_VALUE = 3;
    /**
     * <pre>
     *总控
     * </pre>
     *
     * <code>MANAGER = 10000;</code>
     */
    public static final int MANAGER_VALUE = 10000;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UserType forNumber(int value) {
      switch (value) {
        case 0: return COMMON;
        case 1: return LINE_MANAGER;
        case 2: return LINE_VIP1;
        case 3: return LINE_VIP2;
        case 10000: return MANAGER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserType>() {
            public UserType findValueByNumber(int number) {
              return UserType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserType[] VALUES = values();

    public static UserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.UserType)
  }

  /**
   * Protobuf enum {@code com.z.model.proto.EmailType}
   */
  public enum EmailType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *默认的转账邮件
     * </pre>
     *
     * <code>ET_DEFAULT = 0;</code>
     */
    ET_DEFAULT(0),
    /**
     * <pre>
     *特定邮件
     * </pre>
     *
     * <code>ET_SPECIAL = 1;</code>
     */
    ET_SPECIAL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *默认的转账邮件
     * </pre>
     *
     * <code>ET_DEFAULT = 0;</code>
     */
    public static final int ET_DEFAULT_VALUE = 0;
    /**
     * <pre>
     *特定邮件
     * </pre>
     *
     * <code>ET_SPECIAL = 1;</code>
     */
    public static final int ET_SPECIAL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EmailType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EmailType forNumber(int value) {
      switch (value) {
        case 0: return ET_DEFAULT;
        case 1: return ET_SPECIAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EmailType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EmailType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EmailType>() {
            public EmailType findValueByNumber(int number) {
              return EmailType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.getDescriptor().getEnumTypes().get(1);
    }

    private static final EmailType[] VALUES = values();

    public static EmailType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EmailType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.EmailType)
  }

  /**
   * <pre>
   *通用 0，1 状态
   * </pre>
   *
   * Protobuf enum {@code com.z.model.proto.YesNo}
   */
  public enum YesNo
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *否
     * </pre>
     *
     * <code>YN_N = 0;</code>
     */
    YN_N(0),
    /**
     * <pre>
     *是
     * </pre>
     *
     * <code>YN_Y = 1;</code>
     */
    YN_Y(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *否
     * </pre>
     *
     * <code>YN_N = 0;</code>
     */
    public static final int YN_N_VALUE = 0;
    /**
     * <pre>
     *是
     * </pre>
     *
     * <code>YN_Y = 1;</code>
     */
    public static final int YN_Y_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static YesNo valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static YesNo forNumber(int value) {
      switch (value) {
        case 0: return YN_N;
        case 1: return YN_Y;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<YesNo>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        YesNo> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<YesNo>() {
            public YesNo findValueByNumber(int number) {
              return YesNo.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.getDescriptor().getEnumTypes().get(2);
    }

    private static final YesNo[] VALUES = values();

    public static YesNo valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private YesNo(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.YesNo)
  }

  /**
   * <pre>
   *银行金额变动类型
   * </pre>
   *
   * Protobuf enum {@code com.z.model.proto.BankType}
   */
  public enum BankType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *默认
     * </pre>
     *
     * <code>BT_DEFAULT = 0;</code>
     */
    BT_DEFAULT(0),
    /**
     * <pre>
     *存入
     * </pre>
     *
     * <code>BT_DEPOSIT = 1;</code>
     */
    BT_DEPOSIT(1),
    /**
     * <pre>
     *取出
     * </pre>
     *
     * <code>BT_WITHDRAW = 2;</code>
     */
    BT_WITHDRAW(2),
    /**
     * <pre>
     *转账
     * </pre>
     *
     * <code>BT_TRANSFER = 3;</code>
     */
    BT_TRANSFER(3),
    /**
     * <pre>
     *邮件
     * </pre>
     *
     * <code>BT_EMAIL = 4;</code>
     */
    BT_EMAIL(4),
    /**
     * <pre>
     *兑换码
     * </pre>
     *
     * <code>BT_REDEEM_CODE = 5;</code>
     */
    BT_REDEEM_CODE(5),
    /**
     * <pre>
     *后台
     * </pre>
     *
     * <code>BT_GM = 100;</code>
     */
    BT_GM(100),
    /**
     * <pre>
     *自动
     * </pre>
     *
     * <code>BT_AI = 200;</code>
     */
    BT_AI(200),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *默认
     * </pre>
     *
     * <code>BT_DEFAULT = 0;</code>
     */
    public static final int BT_DEFAULT_VALUE = 0;
    /**
     * <pre>
     *存入
     * </pre>
     *
     * <code>BT_DEPOSIT = 1;</code>
     */
    public static final int BT_DEPOSIT_VALUE = 1;
    /**
     * <pre>
     *取出
     * </pre>
     *
     * <code>BT_WITHDRAW = 2;</code>
     */
    public static final int BT_WITHDRAW_VALUE = 2;
    /**
     * <pre>
     *转账
     * </pre>
     *
     * <code>BT_TRANSFER = 3;</code>
     */
    public static final int BT_TRANSFER_VALUE = 3;
    /**
     * <pre>
     *邮件
     * </pre>
     *
     * <code>BT_EMAIL = 4;</code>
     */
    public static final int BT_EMAIL_VALUE = 4;
    /**
     * <pre>
     *兑换码
     * </pre>
     *
     * <code>BT_REDEEM_CODE = 5;</code>
     */
    public static final int BT_REDEEM_CODE_VALUE = 5;
    /**
     * <pre>
     *后台
     * </pre>
     *
     * <code>BT_GM = 100;</code>
     */
    public static final int BT_GM_VALUE = 100;
    /**
     * <pre>
     *自动
     * </pre>
     *
     * <code>BT_AI = 200;</code>
     */
    public static final int BT_AI_VALUE = 200;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BankType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BankType forNumber(int value) {
      switch (value) {
        case 0: return BT_DEFAULT;
        case 1: return BT_DEPOSIT;
        case 2: return BT_WITHDRAW;
        case 3: return BT_TRANSFER;
        case 4: return BT_EMAIL;
        case 5: return BT_REDEEM_CODE;
        case 100: return BT_GM;
        case 200: return BT_AI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BankType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BankType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BankType>() {
            public BankType findValueByNumber(int number) {
              return BankType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.getDescriptor().getEnumTypes().get(3);
    }

    private static final BankType[] VALUES = values();

    public static BankType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BankType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.BankType)
  }

  /**
   * <pre>
   *银行金额变动类型
   * </pre>
   *
   * Protobuf enum {@code com.z.model.proto.TransferLogType}
   */
  public enum TransferLogType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *默认
     * </pre>
     *
     * <code>TT_DEFAULT = 0;</code>
     */
    TT_DEFAULT(0),
    /**
     * <pre>
     *转账
     * </pre>
     *
     * <code>TT_TRANSFER = 1;</code>
     */
    TT_TRANSFER(1),
    /**
     * <pre>
     *返利
     * </pre>
     *
     * <code>TT_REBET = 2;</code>
     */
    TT_REBET(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *默认
     * </pre>
     *
     * <code>TT_DEFAULT = 0;</code>
     */
    public static final int TT_DEFAULT_VALUE = 0;
    /**
     * <pre>
     *转账
     * </pre>
     *
     * <code>TT_TRANSFER = 1;</code>
     */
    public static final int TT_TRANSFER_VALUE = 1;
    /**
     * <pre>
     *返利
     * </pre>
     *
     * <code>TT_REBET = 2;</code>
     */
    public static final int TT_REBET_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransferLogType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TransferLogType forNumber(int value) {
      switch (value) {
        case 0: return TT_DEFAULT;
        case 1: return TT_TRANSFER;
        case 2: return TT_REBET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransferLogType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransferLogType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransferLogType>() {
            public TransferLogType findValueByNumber(int number) {
              return TransferLogType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.getDescriptor().getEnumTypes().get(4);
    }

    private static final TransferLogType[] VALUES = values();

    public static TransferLogType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransferLogType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.TransferLogType)
  }

  /**
   * <pre>
   *钱包金额变动类型
   * </pre>
   *
   * Protobuf enum {@code com.z.model.proto.GoldType}
   */
  public enum GoldType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *默认
     * </pre>
     *
     * <code>GT_DEAULT = 0;</code>
     */
    GT_DEAULT(0),
    /**
     * <pre>
     *存入
     * </pre>
     *
     * <code>GT_DEPOSIT = 1;</code>
     */
    GT_DEPOSIT(1),
    /**
     * <pre>
     *取出
     * </pre>
     *
     * <code>GT_WITHDRAW = 2;</code>
     */
    GT_WITHDRAW(2),
    /**
     * <pre>
     *邮件
     * </pre>
     *
     * <code>GT_EMAIL = 3;</code>
     */
    GT_EMAIL(3),
    /**
     * <pre>
     *游戏
     * </pre>
     *
     * <code>GT_GAME = 4;</code>
     */
    GT_GAME(4),
    /**
     * <pre>
     *后台
     * </pre>
     *
     * <code>GT_GM = 100;</code>
     */
    GT_GM(100),
    /**
     * <pre>
     *自动
     * </pre>
     *
     * <code>GT_AI = 200;</code>
     */
    GT_AI(200),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *默认
     * </pre>
     *
     * <code>GT_DEAULT = 0;</code>
     */
    public static final int GT_DEAULT_VALUE = 0;
    /**
     * <pre>
     *存入
     * </pre>
     *
     * <code>GT_DEPOSIT = 1;</code>
     */
    public static final int GT_DEPOSIT_VALUE = 1;
    /**
     * <pre>
     *取出
     * </pre>
     *
     * <code>GT_WITHDRAW = 2;</code>
     */
    public static final int GT_WITHDRAW_VALUE = 2;
    /**
     * <pre>
     *邮件
     * </pre>
     *
     * <code>GT_EMAIL = 3;</code>
     */
    public static final int GT_EMAIL_VALUE = 3;
    /**
     * <pre>
     *游戏
     * </pre>
     *
     * <code>GT_GAME = 4;</code>
     */
    public static final int GT_GAME_VALUE = 4;
    /**
     * <pre>
     *后台
     * </pre>
     *
     * <code>GT_GM = 100;</code>
     */
    public static final int GT_GM_VALUE = 100;
    /**
     * <pre>
     *自动
     * </pre>
     *
     * <code>GT_AI = 200;</code>
     */
    public static final int GT_AI_VALUE = 200;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GoldType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GoldType forNumber(int value) {
      switch (value) {
        case 0: return GT_DEAULT;
        case 1: return GT_DEPOSIT;
        case 2: return GT_WITHDRAW;
        case 3: return GT_EMAIL;
        case 4: return GT_GAME;
        case 100: return GT_GM;
        case 200: return GT_AI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GoldType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GoldType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GoldType>() {
            public GoldType findValueByNumber(int number) {
              return GoldType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.getDescriptor().getEnumTypes().get(5);
    }

    private static final GoldType[] VALUES = values();

    public static GoldType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GoldType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.GoldType)
  }

  /**
   * <pre>
   *修改用户信息类型
   * </pre>
   *
   * Protobuf enum {@code com.z.model.proto.ModifyUserType}
   */
  public enum ModifyUserType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *修改名字
     * </pre>
     *
     * <code>MUT_NAME = 0;</code>
     */
    MUT_NAME(0),
    /**
     * <pre>
     *修改头像
     * </pre>
     *
     * <code>MUT_ICON = 1;</code>
     */
    MUT_ICON(1),
    /**
     * <pre>
     *绑定手机号
     * </pre>
     *
     * <code>MUT_PHONE = 2;</code>
     */
    MUT_PHONE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *修改名字
     * </pre>
     *
     * <code>MUT_NAME = 0;</code>
     */
    public static final int MUT_NAME_VALUE = 0;
    /**
     * <pre>
     *修改头像
     * </pre>
     *
     * <code>MUT_ICON = 1;</code>
     */
    public static final int MUT_ICON_VALUE = 1;
    /**
     * <pre>
     *绑定手机号
     * </pre>
     *
     * <code>MUT_PHONE = 2;</code>
     */
    public static final int MUT_PHONE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ModifyUserType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ModifyUserType forNumber(int value) {
      switch (value) {
        case 0: return MUT_NAME;
        case 1: return MUT_ICON;
        case 2: return MUT_PHONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ModifyUserType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ModifyUserType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ModifyUserType>() {
            public ModifyUserType findValueByNumber(int number) {
              return ModifyUserType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.getDescriptor().getEnumTypes().get(6);
    }

    private static final ModifyUserType[] VALUES = values();

    public static ModifyUserType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ModifyUserType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.ModifyUserType)
  }

  /**
   * <pre>
   *点卡状态
   * </pre>
   *
   * Protobuf enum {@code com.z.model.proto.CodeState}
   */
  public enum CodeState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未使用
     * </pre>
     *
     * <code>CS_NOUSE = 0;</code>
     */
    CS_NOUSE(0),
    /**
     * <pre>
     *使用
     * </pre>
     *
     * <code>CS_USE = 1;</code>
     */
    CS_USE(1),
    /**
     * <pre>
     *过期
     * </pre>
     *
     * <code>CS_TIME = 2;</code>
     */
    CS_TIME(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *未使用
     * </pre>
     *
     * <code>CS_NOUSE = 0;</code>
     */
    public static final int CS_NOUSE_VALUE = 0;
    /**
     * <pre>
     *使用
     * </pre>
     *
     * <code>CS_USE = 1;</code>
     */
    public static final int CS_USE_VALUE = 1;
    /**
     * <pre>
     *过期
     * </pre>
     *
     * <code>CS_TIME = 2;</code>
     */
    public static final int CS_TIME_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CodeState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CodeState forNumber(int value) {
      switch (value) {
        case 0: return CS_NOUSE;
        case 1: return CS_USE;
        case 2: return CS_TIME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CodeState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CodeState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CodeState>() {
            public CodeState findValueByNumber(int number) {
              return CodeState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.getDescriptor().getEnumTypes().get(7);
    }

    private static final CodeState[] VALUES = values();

    public static CodeState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CodeState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.z.model.proto.CodeState)
  }

  public interface UserDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.z.model.proto.UserData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    long getUid();

    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * <pre>
   **
   * 公用结构体 --- 用户数据
   * </pre>
   *
   * Protobuf type {@code com.z.model.proto.UserData}
   */
  public static final class UserData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.z.model.proto.UserData)
      UserDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserData.newBuilder() to construct.
    private UserData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserData() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.z.model.proto.CommonUser.internal_static_com_z_model_proto_UserData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.z.model.proto.CommonUser.internal_static_com_z_model_proto_UserData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.z.model.proto.CommonUser.UserData.class, com.z.model.proto.CommonUser.UserData.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名称
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.z.model.proto.CommonUser.UserData)) {
        return super.equals(obj);
      }
      com.z.model.proto.CommonUser.UserData other = (com.z.model.proto.CommonUser.UserData) obj;

      if (getUid()
          != other.getUid()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.z.model.proto.CommonUser.UserData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.z.model.proto.CommonUser.UserData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.z.model.proto.CommonUser.UserData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.z.model.proto.CommonUser.UserData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.z.model.proto.CommonUser.UserData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * 公用结构体 --- 用户数据
     * </pre>
     *
     * Protobuf type {@code com.z.model.proto.UserData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.z.model.proto.UserData)
        com.z.model.proto.CommonUser.UserDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.z.model.proto.CommonUser.internal_static_com_z_model_proto_UserData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.z.model.proto.CommonUser.internal_static_com_z_model_proto_UserData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.z.model.proto.CommonUser.UserData.class, com.z.model.proto.CommonUser.UserData.Builder.class);
      }

      // Construct using com.z.model.proto.CommonUser.UserData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.z.model.proto.CommonUser.internal_static_com_z_model_proto_UserData_descriptor;
      }

      @java.lang.Override
      public com.z.model.proto.CommonUser.UserData getDefaultInstanceForType() {
        return com.z.model.proto.CommonUser.UserData.getDefaultInstance();
      }

      @java.lang.Override
      public com.z.model.proto.CommonUser.UserData build() {
        com.z.model.proto.CommonUser.UserData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.z.model.proto.CommonUser.UserData buildPartial() {
        com.z.model.proto.CommonUser.UserData result = new com.z.model.proto.CommonUser.UserData(this);
        result.uid_ = uid_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.z.model.proto.CommonUser.UserData) {
          return mergeFrom((com.z.model.proto.CommonUser.UserData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.z.model.proto.CommonUser.UserData other) {
        if (other == com.z.model.proto.CommonUser.UserData.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                uid_ = input.readInt64();

                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private long uid_ ;
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @return The uid.
       */
      @java.lang.Override
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名称
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.z.model.proto.UserData)
    }

    // @@protoc_insertion_point(class_scope:com.z.model.proto.UserData)
    private static final com.z.model.proto.CommonUser.UserData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.z.model.proto.CommonUser.UserData();
    }

    public static com.z.model.proto.CommonUser.UserData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserData>
        PARSER = new com.google.protobuf.AbstractParser<UserData>() {
      @java.lang.Override
      public UserData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.z.model.proto.CommonUser.UserData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_z_model_proto_UserData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_z_model_proto_UserData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021common_user.proto\022\021com.z.model.proto\"%" +
      "\n\010UserData\022\013\n\003uid\030\001 \001(\003\022\014\n\004name\030\002 \001(\t*T\n" +
      "\010UserType\022\n\n\006COMMON\020\000\022\020\n\014LINE_MANAGER\020\001\022" +
      "\r\n\tLINE_VIP1\020\002\022\r\n\tLINE_VIP2\020\003\022\014\n\007MANAGER" +
      "\020\220N*+\n\tEmailType\022\016\n\nET_DEFAULT\020\000\022\016\n\nET_S" +
      "PECIAL\020\001*\033\n\005YesNo\022\010\n\004YN_N\020\000\022\010\n\004YN_Y\020\001*\205\001" +
      "\n\010BankType\022\016\n\nBT_DEFAULT\020\000\022\016\n\nBT_DEPOSIT" +
      "\020\001\022\017\n\013BT_WITHDRAW\020\002\022\017\n\013BT_TRANSFER\020\003\022\014\n\010" +
      "BT_EMAIL\020\004\022\022\n\016BT_REDEEM_CODE\020\005\022\t\n\005BT_GM\020" +
      "d\022\n\n\005BT_AI\020\310\001*@\n\017TransferLogType\022\016\n\nTT_D" +
      "EFAULT\020\000\022\017\n\013TT_TRANSFER\020\001\022\014\n\010TT_REBET\020\002*" +
      "l\n\010GoldType\022\r\n\tGT_DEAULT\020\000\022\016\n\nGT_DEPOSIT" +
      "\020\001\022\017\n\013GT_WITHDRAW\020\002\022\014\n\010GT_EMAIL\020\003\022\013\n\007GT_" +
      "GAME\020\004\022\t\n\005GT_GM\020d\022\n\n\005GT_AI\020\310\001*;\n\016ModifyU" +
      "serType\022\014\n\010MUT_NAME\020\000\022\014\n\010MUT_ICON\020\001\022\r\n\tM" +
      "UT_PHONE\020\002*2\n\tCodeState\022\014\n\010CS_NOUSE\020\000\022\n\n" +
      "\006CS_USE\020\001\022\013\n\007CS_TIME\020\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_z_model_proto_UserData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_z_model_proto_UserData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_z_model_proto_UserData_descriptor,
        new java.lang.String[] { "Uid", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
