// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto

package com.z.model.proto;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.z.model.proto.GameMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *数据id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
     * @return Whether the req10001 field is set.
     */
    boolean hasReq10001();
    /**
     * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
     * @return The req10001.
     */
    Game_Req_20001 getReq10001();
    /**
     * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
     */
    Game_Req_20001OrBuilder getReq10001OrBuilder();

    /**
     * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
     * @return Whether the res10002 field is set.
     */
    boolean hasRes10002();
    /**
     * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
     * @return The res10002.
     */
    Game_Res_20002 getRes10002();
    /**
     * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
     */
    Game_Res_20002OrBuilder getRes10002OrBuilder();

    public GameMsg.TypeCase getTypeCase();
  }
  /**
   * <pre>
   *玩法消息
   * </pre>
   *
   * Protobuf type {@code com.z.model.proto.GameMsg}
   */
  public static final class GameMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.z.model.proto.GameMsg)
      GameMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GameMsg.newBuilder() to construct.
    private GameMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameMsg() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new GameMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Game.internal_static_com_z_model_proto_GameMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Game.internal_static_com_z_model_proto_GameMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GameMsg.class, Builder.class);
    }

    private int typeCase_ = 0;
    private Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      REQ10001(2),
      RES10002(3),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 2: return REQ10001;
          case 3: return RES10002;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *数据id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int REQ10001_FIELD_NUMBER = 2;
    /**
     * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
     * @return Whether the req10001 field is set.
     */
    @Override
    public boolean hasReq10001() {
      return typeCase_ == 2;
    }
    /**
     * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
     * @return The req10001.
     */
    @Override
    public Game_Req_20001 getReq10001() {
      if (typeCase_ == 2) {
         return (Game_Req_20001) type_;
      }
      return Game_Req_20001.getDefaultInstance();
    }
    /**
     * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
     */
    @Override
    public Game_Req_20001OrBuilder getReq10001OrBuilder() {
      if (typeCase_ == 2) {
         return (Game_Req_20001) type_;
      }
      return Game_Req_20001.getDefaultInstance();
    }

    public static final int RES10002_FIELD_NUMBER = 3;
    /**
     * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
     * @return Whether the res10002 field is set.
     */
    @Override
    public boolean hasRes10002() {
      return typeCase_ == 3;
    }
    /**
     * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
     * @return The res10002.
     */
    @Override
    public Game_Res_20002 getRes10002() {
      if (typeCase_ == 3) {
         return (Game_Res_20002) type_;
      }
      return Game_Res_20002.getDefaultInstance();
    }
    /**
     * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
     */
    @Override
    public Game_Res_20002OrBuilder getRes10002OrBuilder() {
      if (typeCase_ == 3) {
         return (Game_Res_20002) type_;
      }
      return Game_Res_20002.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (typeCase_ == 2) {
        output.writeMessage(2, (Game_Req_20001) type_);
      }
      if (typeCase_ == 3) {
        output.writeMessage(3, (Game_Res_20002) type_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Game_Req_20001) type_);
      }
      if (typeCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Game_Res_20002) type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GameMsg)) {
        return super.equals(obj);
      }
      GameMsg other = (GameMsg) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTypeCase().equals(other.getTypeCase())) return false;
      switch (typeCase_) {
        case 2:
          if (!getReq10001()
              .equals(other.getReq10001())) return false;
          break;
        case 3:
          if (!getRes10002()
              .equals(other.getRes10002())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      switch (typeCase_) {
        case 2:
          hash = (37 * hash) + REQ10001_FIELD_NUMBER;
          hash = (53 * hash) + getReq10001().hashCode();
          break;
        case 3:
          hash = (37 * hash) + RES10002_FIELD_NUMBER;
          hash = (53 * hash) + getRes10002().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GameMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GameMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GameMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GameMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GameMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GameMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GameMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *玩法消息
     * </pre>
     *
     * Protobuf type {@code com.z.model.proto.GameMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.z.model.proto.GameMsg)
        GameMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Game.internal_static_com_z_model_proto_GameMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Game.internal_static_com_z_model_proto_GameMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GameMsg.class, Builder.class);
      }

      // Construct using com.z.model.proto.Game.GameMsg.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        if (req10001Builder_ != null) {
          req10001Builder_.clear();
        }
        if (res10002Builder_ != null) {
          res10002Builder_.clear();
        }
        typeCase_ = 0;
        type_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Game.internal_static_com_z_model_proto_GameMsg_descriptor;
      }

      @Override
      public GameMsg getDefaultInstanceForType() {
        return GameMsg.getDefaultInstance();
      }

      @Override
      public GameMsg build() {
        GameMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public GameMsg buildPartial() {
        GameMsg result = new GameMsg(this);
        result.id_ = id_;
        if (typeCase_ == 2) {
          if (req10001Builder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = req10001Builder_.build();
          }
        }
        if (typeCase_ == 3) {
          if (res10002Builder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = res10002Builder_.build();
          }
        }
        result.typeCase_ = typeCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GameMsg) {
          return mergeFrom((GameMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GameMsg other) {
        if (other == GameMsg.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        switch (other.getTypeCase()) {
          case REQ10001: {
            mergeReq10001(other.getReq10001());
            break;
          }
          case RES10002: {
            mergeRes10002(other.getRes10002());
            break;
          }
          case TYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();

                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getReq10001FieldBuilder().getBuilder(),
                    extensionRegistry);
                typeCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getRes10002FieldBuilder().getBuilder(),
                    extensionRegistry);
                typeCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int typeCase_ = 0;
      private Object type_;
      public TypeCase
          getTypeCase() {
        return TypeCase.forNumber(
            typeCase_);
      }

      public Builder clearType() {
        typeCase_ = 0;
        type_ = null;
        onChanged();
        return this;
      }


      private long id_ ;
      /**
       * <pre>
       *数据id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *数据id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据id
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Game_Req_20001, Game_Req_20001.Builder, Game_Req_20001OrBuilder> req10001Builder_;
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       * @return Whether the req10001 field is set.
       */
      @Override
      public boolean hasReq10001() {
        return typeCase_ == 2;
      }
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       * @return The req10001.
       */
      @Override
      public Game_Req_20001 getReq10001() {
        if (req10001Builder_ == null) {
          if (typeCase_ == 2) {
            return (Game_Req_20001) type_;
          }
          return Game_Req_20001.getDefaultInstance();
        } else {
          if (typeCase_ == 2) {
            return req10001Builder_.getMessage();
          }
          return Game_Req_20001.getDefaultInstance();
        }
      }
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       */
      public Builder setReq10001(Game_Req_20001 value) {
        if (req10001Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          req10001Builder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       */
      public Builder setReq10001(
          Game_Req_20001.Builder builderForValue) {
        if (req10001Builder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          req10001Builder_.setMessage(builderForValue.build());
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       */
      public Builder mergeReq10001(Game_Req_20001 value) {
        if (req10001Builder_ == null) {
          if (typeCase_ == 2 &&
              type_ != Game_Req_20001.getDefaultInstance()) {
            type_ = Game_Req_20001.newBuilder((Game_Req_20001) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 2) {
            req10001Builder_.mergeFrom(value);
          } else {
            req10001Builder_.setMessage(value);
          }
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       */
      public Builder clearReq10001() {
        if (req10001Builder_ == null) {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
          }
          req10001Builder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       */
      public Game_Req_20001.Builder getReq10001Builder() {
        return getReq10001FieldBuilder().getBuilder();
      }
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       */
      @Override
      public Game_Req_20001OrBuilder getReq10001OrBuilder() {
        if ((typeCase_ == 2) && (req10001Builder_ != null)) {
          return req10001Builder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 2) {
            return (Game_Req_20001) type_;
          }
          return Game_Req_20001.getDefaultInstance();
        }
      }
      /**
       * <code>.com.z.model.proto.Game_Req_20001 req10001 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Game_Req_20001, Game_Req_20001.Builder, Game_Req_20001OrBuilder>
          getReq10001FieldBuilder() {
        if (req10001Builder_ == null) {
          if (!(typeCase_ == 2)) {
            type_ = Game_Req_20001.getDefaultInstance();
          }
          req10001Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Game_Req_20001, Game_Req_20001.Builder, Game_Req_20001OrBuilder>(
                  (Game_Req_20001) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 2;
        onChanged();;
        return req10001Builder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Game_Res_20002, Game_Res_20002.Builder, Game_Res_20002OrBuilder> res10002Builder_;
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       * @return Whether the res10002 field is set.
       */
      @Override
      public boolean hasRes10002() {
        return typeCase_ == 3;
      }
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       * @return The res10002.
       */
      @Override
      public Game_Res_20002 getRes10002() {
        if (res10002Builder_ == null) {
          if (typeCase_ == 3) {
            return (Game_Res_20002) type_;
          }
          return Game_Res_20002.getDefaultInstance();
        } else {
          if (typeCase_ == 3) {
            return res10002Builder_.getMessage();
          }
          return Game_Res_20002.getDefaultInstance();
        }
      }
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       */
      public Builder setRes10002(Game_Res_20002 value) {
        if (res10002Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          res10002Builder_.setMessage(value);
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       */
      public Builder setRes10002(
          Game_Res_20002.Builder builderForValue) {
        if (res10002Builder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          res10002Builder_.setMessage(builderForValue.build());
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       */
      public Builder mergeRes10002(Game_Res_20002 value) {
        if (res10002Builder_ == null) {
          if (typeCase_ == 3 &&
              type_ != Game_Res_20002.getDefaultInstance()) {
            type_ = Game_Res_20002.newBuilder((Game_Res_20002) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 3) {
            res10002Builder_.mergeFrom(value);
          } else {
            res10002Builder_.setMessage(value);
          }
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       */
      public Builder clearRes10002() {
        if (res10002Builder_ == null) {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
          }
          res10002Builder_.clear();
        }
        return this;
      }
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       */
      public Game_Res_20002.Builder getRes10002Builder() {
        return getRes10002FieldBuilder().getBuilder();
      }
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       */
      @Override
      public Game_Res_20002OrBuilder getRes10002OrBuilder() {
        if ((typeCase_ == 3) && (res10002Builder_ != null)) {
          return res10002Builder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 3) {
            return (Game_Res_20002) type_;
          }
          return Game_Res_20002.getDefaultInstance();
        }
      }
      /**
       * <code>.com.z.model.proto.Game_Res_20002 res10002 = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Game_Res_20002, Game_Res_20002.Builder, Game_Res_20002OrBuilder>
          getRes10002FieldBuilder() {
        if (res10002Builder_ == null) {
          if (!(typeCase_ == 3)) {
            type_ = Game_Res_20002.getDefaultInstance();
          }
          res10002Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Game_Res_20002, Game_Res_20002.Builder, Game_Res_20002OrBuilder>(
                  (Game_Res_20002) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 3;
        onChanged();;
        return res10002Builder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.z.model.proto.GameMsg)
    }

    // @@protoc_insertion_point(class_scope:com.z.model.proto.GameMsg)
    private static final GameMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GameMsg();
    }

    public static GameMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameMsg>
        PARSER = new com.google.protobuf.AbstractParser<GameMsg>() {
      @Override
      public GameMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GameMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GameMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public GameMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Game_Req_20001OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.z.model.proto.Game_Req_20001)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *麻将
     * </pre>
     *
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     * @return Whether the mahjongData field is set.
     */
    boolean hasMahjongData();
    /**
     * <pre>
     *麻将
     * </pre>
     *
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     * @return The mahjongData.
     */
    CommonGame.MahjongData getMahjongData();
    /**
     * <pre>
     *麻将
     * </pre>
     *
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     */
    CommonGame.MahjongDataOrBuilder getMahjongDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.z.model.proto.Game_Req_20001}
   */
  public static final class Game_Req_20001 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.z.model.proto.Game_Req_20001)
      Game_Req_20001OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Game_Req_20001.newBuilder() to construct.
    private Game_Req_20001(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Game_Req_20001() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Game_Req_20001();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Game.internal_static_com_z_model_proto_Game_Req_20001_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Game.internal_static_com_z_model_proto_Game_Req_20001_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Game_Req_20001.class, Builder.class);
    }

    public static final int MAHJONGDATA_FIELD_NUMBER = 1;
    private CommonGame.MahjongData mahjongData_;
    /**
     * <pre>
     *麻将
     * </pre>
     *
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     * @return Whether the mahjongData field is set.
     */
    @Override
    public boolean hasMahjongData() {
      return mahjongData_ != null;
    }
    /**
     * <pre>
     *麻将
     * </pre>
     *
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     * @return The mahjongData.
     */
    @Override
    public CommonGame.MahjongData getMahjongData() {
      return mahjongData_ == null ? CommonGame.MahjongData.getDefaultInstance() : mahjongData_;
    }
    /**
     * <pre>
     *麻将
     * </pre>
     *
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     */
    @Override
    public CommonGame.MahjongDataOrBuilder getMahjongDataOrBuilder() {
      return getMahjongData();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mahjongData_ != null) {
        output.writeMessage(1, getMahjongData());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mahjongData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMahjongData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Game_Req_20001)) {
        return super.equals(obj);
      }
      Game_Req_20001 other = (Game_Req_20001) obj;

      if (hasMahjongData() != other.hasMahjongData()) return false;
      if (hasMahjongData()) {
        if (!getMahjongData()
            .equals(other.getMahjongData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMahjongData()) {
        hash = (37 * hash) + MAHJONGDATA_FIELD_NUMBER;
        hash = (53 * hash) + getMahjongData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Game_Req_20001 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Game_Req_20001 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Game_Req_20001 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Game_Req_20001 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Game_Req_20001 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Game_Req_20001 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Game_Req_20001 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Game_Req_20001 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Game_Req_20001 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Game_Req_20001 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Game_Req_20001 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Game_Req_20001 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Game_Req_20001 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.z.model.proto.Game_Req_20001}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.z.model.proto.Game_Req_20001)
        Game_Req_20001OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Game.internal_static_com_z_model_proto_Game_Req_20001_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Game.internal_static_com_z_model_proto_Game_Req_20001_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Game_Req_20001.class, Builder.class);
      }

      // Construct using com.z.model.proto.Game.Game_Req_20001.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        if (mahjongDataBuilder_ == null) {
          mahjongData_ = null;
        } else {
          mahjongData_ = null;
          mahjongDataBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Game.internal_static_com_z_model_proto_Game_Req_20001_descriptor;
      }

      @Override
      public Game_Req_20001 getDefaultInstanceForType() {
        return Game_Req_20001.getDefaultInstance();
      }

      @Override
      public Game_Req_20001 build() {
        Game_Req_20001 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Game_Req_20001 buildPartial() {
        Game_Req_20001 result = new Game_Req_20001(this);
        if (mahjongDataBuilder_ == null) {
          result.mahjongData_ = mahjongData_;
        } else {
          result.mahjongData_ = mahjongDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Game_Req_20001) {
          return mergeFrom((Game_Req_20001)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Game_Req_20001 other) {
        if (other == Game_Req_20001.getDefaultInstance()) return this;
        if (other.hasMahjongData()) {
          mergeMahjongData(other.getMahjongData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMahjongDataFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private CommonGame.MahjongData mahjongData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonGame.MahjongData, CommonGame.MahjongData.Builder, CommonGame.MahjongDataOrBuilder> mahjongDataBuilder_;
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       * @return Whether the mahjongData field is set.
       */
      public boolean hasMahjongData() {
        return mahjongDataBuilder_ != null || mahjongData_ != null;
      }
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       * @return The mahjongData.
       */
      public CommonGame.MahjongData getMahjongData() {
        if (mahjongDataBuilder_ == null) {
          return mahjongData_ == null ? CommonGame.MahjongData.getDefaultInstance() : mahjongData_;
        } else {
          return mahjongDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public Builder setMahjongData(CommonGame.MahjongData value) {
        if (mahjongDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mahjongData_ = value;
          onChanged();
        } else {
          mahjongDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public Builder setMahjongData(
          CommonGame.MahjongData.Builder builderForValue) {
        if (mahjongDataBuilder_ == null) {
          mahjongData_ = builderForValue.build();
          onChanged();
        } else {
          mahjongDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public Builder mergeMahjongData(CommonGame.MahjongData value) {
        if (mahjongDataBuilder_ == null) {
          if (mahjongData_ != null) {
            mahjongData_ =
              CommonGame.MahjongData.newBuilder(mahjongData_).mergeFrom(value).buildPartial();
          } else {
            mahjongData_ = value;
          }
          onChanged();
        } else {
          mahjongDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public Builder clearMahjongData() {
        if (mahjongDataBuilder_ == null) {
          mahjongData_ = null;
          onChanged();
        } else {
          mahjongData_ = null;
          mahjongDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public CommonGame.MahjongData.Builder getMahjongDataBuilder() {
        
        onChanged();
        return getMahjongDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public CommonGame.MahjongDataOrBuilder getMahjongDataOrBuilder() {
        if (mahjongDataBuilder_ != null) {
          return mahjongDataBuilder_.getMessageOrBuilder();
        } else {
          return mahjongData_ == null ?
              CommonGame.MahjongData.getDefaultInstance() : mahjongData_;
        }
      }
      /**
       * <pre>
       *麻将
       * </pre>
       *
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonGame.MahjongData, CommonGame.MahjongData.Builder, CommonGame.MahjongDataOrBuilder>
          getMahjongDataFieldBuilder() {
        if (mahjongDataBuilder_ == null) {
          mahjongDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommonGame.MahjongData, CommonGame.MahjongData.Builder, CommonGame.MahjongDataOrBuilder>(
                  getMahjongData(),
                  getParentForChildren(),
                  isClean());
          mahjongData_ = null;
        }
        return mahjongDataBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.z.model.proto.Game_Req_20001)
    }

    // @@protoc_insertion_point(class_scope:com.z.model.proto.Game_Req_20001)
    private static final Game_Req_20001 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Game_Req_20001();
    }

    public static Game_Req_20001 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Game_Req_20001>
        PARSER = new com.google.protobuf.AbstractParser<Game_Req_20001>() {
      @Override
      public Game_Req_20001 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Game_Req_20001> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Game_Req_20001> getParserForType() {
      return PARSER;
    }

    @Override
    public Game_Req_20001 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Game_Res_20002OrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.z.model.proto.Game_Res_20002)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     * @return Whether the mahjongData field is set.
     */
    boolean hasMahjongData();
    /**
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     * @return The mahjongData.
     */
    CommonGame.MahjongData getMahjongData();
    /**
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     */
    CommonGame.MahjongDataOrBuilder getMahjongDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.z.model.proto.Game_Res_20002}
   */
  public static final class Game_Res_20002 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.z.model.proto.Game_Res_20002)
      Game_Res_20002OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Game_Res_20002.newBuilder() to construct.
    private Game_Res_20002(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Game_Res_20002() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Game_Res_20002();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Game.internal_static_com_z_model_proto_Game_Res_20002_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Game.internal_static_com_z_model_proto_Game_Res_20002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Game_Res_20002.class, Builder.class);
    }

    public static final int MAHJONGDATA_FIELD_NUMBER = 1;
    private CommonGame.MahjongData mahjongData_;
    /**
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     * @return Whether the mahjongData field is set.
     */
    @Override
    public boolean hasMahjongData() {
      return mahjongData_ != null;
    }
    /**
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     * @return The mahjongData.
     */
    @Override
    public CommonGame.MahjongData getMahjongData() {
      return mahjongData_ == null ? CommonGame.MahjongData.getDefaultInstance() : mahjongData_;
    }
    /**
     * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
     */
    @Override
    public CommonGame.MahjongDataOrBuilder getMahjongDataOrBuilder() {
      return getMahjongData();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mahjongData_ != null) {
        output.writeMessage(1, getMahjongData());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mahjongData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMahjongData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Game_Res_20002)) {
        return super.equals(obj);
      }
      Game_Res_20002 other = (Game_Res_20002) obj;

      if (hasMahjongData() != other.hasMahjongData()) return false;
      if (hasMahjongData()) {
        if (!getMahjongData()
            .equals(other.getMahjongData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMahjongData()) {
        hash = (37 * hash) + MAHJONGDATA_FIELD_NUMBER;
        hash = (53 * hash) + getMahjongData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Game_Res_20002 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Game_Res_20002 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Game_Res_20002 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Game_Res_20002 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Game_Res_20002 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Game_Res_20002 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Game_Res_20002 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Game_Res_20002 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Game_Res_20002 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Game_Res_20002 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Game_Res_20002 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Game_Res_20002 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Game_Res_20002 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.z.model.proto.Game_Res_20002}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.z.model.proto.Game_Res_20002)
        Game_Res_20002OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Game.internal_static_com_z_model_proto_Game_Res_20002_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Game.internal_static_com_z_model_proto_Game_Res_20002_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Game_Res_20002.class, Builder.class);
      }

      // Construct using com.z.model.proto.Game.Game_Res_20002.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        if (mahjongDataBuilder_ == null) {
          mahjongData_ = null;
        } else {
          mahjongData_ = null;
          mahjongDataBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Game.internal_static_com_z_model_proto_Game_Res_20002_descriptor;
      }

      @Override
      public Game_Res_20002 getDefaultInstanceForType() {
        return Game_Res_20002.getDefaultInstance();
      }

      @Override
      public Game_Res_20002 build() {
        Game_Res_20002 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Game_Res_20002 buildPartial() {
        Game_Res_20002 result = new Game_Res_20002(this);
        if (mahjongDataBuilder_ == null) {
          result.mahjongData_ = mahjongData_;
        } else {
          result.mahjongData_ = mahjongDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Game_Res_20002) {
          return mergeFrom((Game_Res_20002)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Game_Res_20002 other) {
        if (other == Game_Res_20002.getDefaultInstance()) return this;
        if (other.hasMahjongData()) {
          mergeMahjongData(other.getMahjongData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMahjongDataFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private CommonGame.MahjongData mahjongData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonGame.MahjongData, CommonGame.MahjongData.Builder, CommonGame.MahjongDataOrBuilder> mahjongDataBuilder_;
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       * @return Whether the mahjongData field is set.
       */
      public boolean hasMahjongData() {
        return mahjongDataBuilder_ != null || mahjongData_ != null;
      }
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       * @return The mahjongData.
       */
      public CommonGame.MahjongData getMahjongData() {
        if (mahjongDataBuilder_ == null) {
          return mahjongData_ == null ? CommonGame.MahjongData.getDefaultInstance() : mahjongData_;
        } else {
          return mahjongDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public Builder setMahjongData(CommonGame.MahjongData value) {
        if (mahjongDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mahjongData_ = value;
          onChanged();
        } else {
          mahjongDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public Builder setMahjongData(
          CommonGame.MahjongData.Builder builderForValue) {
        if (mahjongDataBuilder_ == null) {
          mahjongData_ = builderForValue.build();
          onChanged();
        } else {
          mahjongDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public Builder mergeMahjongData(CommonGame.MahjongData value) {
        if (mahjongDataBuilder_ == null) {
          if (mahjongData_ != null) {
            mahjongData_ =
              CommonGame.MahjongData.newBuilder(mahjongData_).mergeFrom(value).buildPartial();
          } else {
            mahjongData_ = value;
          }
          onChanged();
        } else {
          mahjongDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public Builder clearMahjongData() {
        if (mahjongDataBuilder_ == null) {
          mahjongData_ = null;
          onChanged();
        } else {
          mahjongData_ = null;
          mahjongDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public CommonGame.MahjongData.Builder getMahjongDataBuilder() {
        
        onChanged();
        return getMahjongDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      public CommonGame.MahjongDataOrBuilder getMahjongDataOrBuilder() {
        if (mahjongDataBuilder_ != null) {
          return mahjongDataBuilder_.getMessageOrBuilder();
        } else {
          return mahjongData_ == null ?
              CommonGame.MahjongData.getDefaultInstance() : mahjongData_;
        }
      }
      /**
       * <code>.com.z.model.proto.MahjongData mahjongData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommonGame.MahjongData, CommonGame.MahjongData.Builder, CommonGame.MahjongDataOrBuilder>
          getMahjongDataFieldBuilder() {
        if (mahjongDataBuilder_ == null) {
          mahjongDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommonGame.MahjongData, CommonGame.MahjongData.Builder, CommonGame.MahjongDataOrBuilder>(
                  getMahjongData(),
                  getParentForChildren(),
                  isClean());
          mahjongData_ = null;
        }
        return mahjongDataBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.z.model.proto.Game_Res_20002)
    }

    // @@protoc_insertion_point(class_scope:com.z.model.proto.Game_Res_20002)
    private static final Game_Res_20002 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Game_Res_20002();
    }

    public static Game_Res_20002 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Game_Res_20002>
        PARSER = new com.google.protobuf.AbstractParser<Game_Res_20002>() {
      @Override
      public Game_Res_20002 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Game_Res_20002> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Game_Res_20002> getParserForType() {
      return PARSER;
    }

    @Override
    public Game_Res_20002 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_z_model_proto_GameMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_z_model_proto_GameMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_z_model_proto_Game_Req_20001_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_z_model_proto_Game_Req_20001_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_z_model_proto_Game_Res_20002_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_z_model_proto_Game_Res_20002_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nGame.proto\022\021com.z.model.proto\032\021common_" +
      "game.proto\"\213\001\n\007GameMsg\022\n\n\002id\030\001 \001(\003\0225\n\010re" +
      "q10001\030\002 \001(\0132!.com.z.model.proto.Game_Re" +
      "q_20001H\000\0225\n\010res10002\030\003 \001(\0132!.com.z.mode" +
      "l.proto.Game_Res_20002H\000B\006\n\004type\"E\n\016Game" +
      "_Req_20001\0223\n\013mahjongData\030\001 \001(\0132\036.com.z." +
      "model.proto.MahjongData\"E\n\016Game_Res_2000" +
      "2\0223\n\013mahjongData\030\001 \001(\0132\036.com.z.model.pro" +
      "to.MahjongDatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CommonGame.getDescriptor(),
        });
    internal_static_com_z_model_proto_GameMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_z_model_proto_GameMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_z_model_proto_GameMsg_descriptor,
        new String[] { "Id", "Req10001", "Res10002", "Type", });
    internal_static_com_z_model_proto_Game_Req_20001_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_z_model_proto_Game_Req_20001_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_z_model_proto_Game_Req_20001_descriptor,
        new String[] { "MahjongData", });
    internal_static_com_z_model_proto_Game_Res_20002_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_z_model_proto_Game_Res_20002_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_z_model_proto_Game_Res_20002_descriptor,
        new String[] { "MahjongData", });
    CommonGame.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
