// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMessage.proto

package com.z.model.proto;

public final class MyMessageOuterClass {
  private MyMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.z.model.proto.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息号
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * 用户 User
     * </pre>
     *
     * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
     * @return Whether the userMsg field is set.
     */
    boolean hasUserMsg();
    /**
     * <pre>
     * 用户 User
     * </pre>
     *
     * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
     * @return The userMsg.
     */
    User.UserMsg getUserMsg();
    /**
     * <pre>
     * 用户 User
     * </pre>
     *
     * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
     */
    User.UserMsgOrBuilder getUserMsgOrBuilder();

    /**
     * <pre>
     *  玩法 game
     * </pre>
     *
     * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
     * @return Whether the gameMsg field is set.
     */
    boolean hasGameMsg();
    /**
     * <pre>
     *  玩法 game
     * </pre>
     *
     * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
     * @return The gameMsg.
     */
    Game.GameMsg getGameMsg();
    /**
     * <pre>
     *  玩法 game
     * </pre>
     *
     * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
     */
    Game.GameMsgOrBuilder getGameMsgOrBuilder();

    public MyMessage.TypeCase getTypeCase();
  }
  /**
   * Protobuf type {@code com.z.model.proto.MyMessage}
   */
  public static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.z.model.proto.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyMessageOuterClass.internal_static_com_z_model_proto_MyMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyMessageOuterClass.internal_static_com_z_model_proto_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyMessage.class, Builder.class);
    }

    private int typeCase_ = 0;
    private Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
      USERMSG(2),
      GAMEMSG(3),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 2: return USERMSG;
          case 3: return GAMEMSG;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     *消息号
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    public static final int USERMSG_FIELD_NUMBER = 2;
    /**
     * <pre>
     * 用户 User
     * </pre>
     *
     * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
     * @return Whether the userMsg field is set.
     */
    @Override
    public boolean hasUserMsg() {
      return typeCase_ == 2;
    }
    /**
     * <pre>
     * 用户 User
     * </pre>
     *
     * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
     * @return The userMsg.
     */
    @Override
    public User.UserMsg getUserMsg() {
      if (typeCase_ == 2) {
         return (User.UserMsg) type_;
      }
      return User.UserMsg.getDefaultInstance();
    }
    /**
     * <pre>
     * 用户 User
     * </pre>
     *
     * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
     */
    @Override
    public User.UserMsgOrBuilder getUserMsgOrBuilder() {
      if (typeCase_ == 2) {
         return (User.UserMsg) type_;
      }
      return User.UserMsg.getDefaultInstance();
    }

    public static final int GAMEMSG_FIELD_NUMBER = 3;
    /**
     * <pre>
     *  玩法 game
     * </pre>
     *
     * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
     * @return Whether the gameMsg field is set.
     */
    @Override
    public boolean hasGameMsg() {
      return typeCase_ == 3;
    }
    /**
     * <pre>
     *  玩法 game
     * </pre>
     *
     * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
     * @return The gameMsg.
     */
    @Override
    public Game.GameMsg getGameMsg() {
      if (typeCase_ == 3) {
         return (Game.GameMsg) type_;
      }
      return Game.GameMsg.getDefaultInstance();
    }
    /**
     * <pre>
     *  玩法 game
     * </pre>
     *
     * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
     */
    @Override
    public Game.GameMsgOrBuilder getGameMsgOrBuilder() {
      if (typeCase_ == 3) {
         return (Game.GameMsg) type_;
      }
      return Game.GameMsg.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (typeCase_ == 2) {
        output.writeMessage(2, (User.UserMsg) type_);
      }
      if (typeCase_ == 3) {
        output.writeMessage(3, (Game.GameMsg) type_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (typeCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (User.UserMsg) type_);
      }
      if (typeCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Game.GameMsg) type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyMessage)) {
        return super.equals(obj);
      }
      MyMessage other = (MyMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTypeCase().equals(other.getTypeCase())) return false;
      switch (typeCase_) {
        case 2:
          if (!getUserMsg()
              .equals(other.getUserMsg())) return false;
          break;
        case 3:
          if (!getGameMsg()
              .equals(other.getGameMsg())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      switch (typeCase_) {
        case 2:
          hash = (37 * hash) + USERMSG_FIELD_NUMBER;
          hash = (53 * hash) + getUserMsg().hashCode();
          break;
        case 3:
          hash = (37 * hash) + GAMEMSG_FIELD_NUMBER;
          hash = (53 * hash) + getGameMsg().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.z.model.proto.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.z.model.proto.MyMessage)
        MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyMessageOuterClass.internal_static_com_z_model_proto_MyMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyMessageOuterClass.internal_static_com_z_model_proto_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyMessage.class, Builder.class);
      }

      // Construct using com.z.model.proto.MyMessageOuterClass.MyMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        if (userMsgBuilder_ != null) {
          userMsgBuilder_.clear();
        }
        if (gameMsgBuilder_ != null) {
          gameMsgBuilder_.clear();
        }
        typeCase_ = 0;
        type_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyMessageOuterClass.internal_static_com_z_model_proto_MyMessage_descriptor;
      }

      @Override
      public MyMessage getDefaultInstanceForType() {
        return MyMessage.getDefaultInstance();
      }

      @Override
      public MyMessage build() {
        MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MyMessage buildPartial() {
        MyMessage result = new MyMessage(this);
        result.id_ = id_;
        if (typeCase_ == 2) {
          if (userMsgBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = userMsgBuilder_.build();
          }
        }
        if (typeCase_ == 3) {
          if (gameMsgBuilder_ == null) {
            result.type_ = type_;
          } else {
            result.type_ = gameMsgBuilder_.build();
          }
        }
        result.typeCase_ = typeCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyMessage) {
          return mergeFrom((MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyMessage other) {
        if (other == MyMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        switch (other.getTypeCase()) {
          case USERMSG: {
            mergeUserMsg(other.getUserMsg());
            break;
          }
          case GAMEMSG: {
            mergeGameMsg(other.getGameMsg());
            break;
          }
          case TYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();

                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getUserMsgFieldBuilder().getBuilder(),
                    extensionRegistry);
                typeCase_ = 2;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getGameMsgFieldBuilder().getBuilder(),
                    extensionRegistry);
                typeCase_ = 3;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int typeCase_ = 0;
      private Object type_;
      public TypeCase
          getTypeCase() {
        return TypeCase.forNumber(
            typeCase_);
      }

      public Builder clearType() {
        typeCase_ = 0;
        type_ = null;
        onChanged();
        return this;
      }


      private int id_ ;
      /**
       * <pre>
       *消息号
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       *消息号
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息号
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          User.UserMsg, User.UserMsg.Builder, User.UserMsgOrBuilder> userMsgBuilder_;
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       * @return Whether the userMsg field is set.
       */
      @Override
      public boolean hasUserMsg() {
        return typeCase_ == 2;
      }
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       * @return The userMsg.
       */
      @Override
      public User.UserMsg getUserMsg() {
        if (userMsgBuilder_ == null) {
          if (typeCase_ == 2) {
            return (User.UserMsg) type_;
          }
          return User.UserMsg.getDefaultInstance();
        } else {
          if (typeCase_ == 2) {
            return userMsgBuilder_.getMessage();
          }
          return User.UserMsg.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       */
      public Builder setUserMsg(User.UserMsg value) {
        if (userMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          userMsgBuilder_.setMessage(value);
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       */
      public Builder setUserMsg(
          User.UserMsg.Builder builderForValue) {
        if (userMsgBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          userMsgBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       */
      public Builder mergeUserMsg(User.UserMsg value) {
        if (userMsgBuilder_ == null) {
          if (typeCase_ == 2 &&
              type_ != User.UserMsg.getDefaultInstance()) {
            type_ = User.UserMsg.newBuilder((User.UserMsg) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 2) {
            userMsgBuilder_.mergeFrom(value);
          } else {
            userMsgBuilder_.setMessage(value);
          }
        }
        typeCase_ = 2;
        return this;
      }
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       */
      public Builder clearUserMsg() {
        if (userMsgBuilder_ == null) {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 2) {
            typeCase_ = 0;
            type_ = null;
          }
          userMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       */
      public User.UserMsg.Builder getUserMsgBuilder() {
        return getUserMsgFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       */
      @Override
      public User.UserMsgOrBuilder getUserMsgOrBuilder() {
        if ((typeCase_ == 2) && (userMsgBuilder_ != null)) {
          return userMsgBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 2) {
            return (User.UserMsg) type_;
          }
          return User.UserMsg.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * 用户 User
       * </pre>
       *
       * <code>.com.z.model.proto.UserMsg userMsg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          User.UserMsg, User.UserMsg.Builder, User.UserMsgOrBuilder>
          getUserMsgFieldBuilder() {
        if (userMsgBuilder_ == null) {
          if (!(typeCase_ == 2)) {
            type_ = User.UserMsg.getDefaultInstance();
          }
          userMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              User.UserMsg, User.UserMsg.Builder, User.UserMsgOrBuilder>(
                  (User.UserMsg) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 2;
        onChanged();;
        return userMsgBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Game.GameMsg, Game.GameMsg.Builder, Game.GameMsgOrBuilder> gameMsgBuilder_;
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       * @return Whether the gameMsg field is set.
       */
      @Override
      public boolean hasGameMsg() {
        return typeCase_ == 3;
      }
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       * @return The gameMsg.
       */
      @Override
      public Game.GameMsg getGameMsg() {
        if (gameMsgBuilder_ == null) {
          if (typeCase_ == 3) {
            return (Game.GameMsg) type_;
          }
          return Game.GameMsg.getDefaultInstance();
        } else {
          if (typeCase_ == 3) {
            return gameMsgBuilder_.getMessage();
          }
          return Game.GameMsg.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       */
      public Builder setGameMsg(Game.GameMsg value) {
        if (gameMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          gameMsgBuilder_.setMessage(value);
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       */
      public Builder setGameMsg(
          Game.GameMsg.Builder builderForValue) {
        if (gameMsgBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          gameMsgBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       */
      public Builder mergeGameMsg(Game.GameMsg value) {
        if (gameMsgBuilder_ == null) {
          if (typeCase_ == 3 &&
              type_ != Game.GameMsg.getDefaultInstance()) {
            type_ = Game.GameMsg.newBuilder((Game.GameMsg) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 3) {
            gameMsgBuilder_.mergeFrom(value);
          } else {
            gameMsgBuilder_.setMessage(value);
          }
        }
        typeCase_ = 3;
        return this;
      }
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       */
      public Builder clearGameMsg() {
        if (gameMsgBuilder_ == null) {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 3) {
            typeCase_ = 0;
            type_ = null;
          }
          gameMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       */
      public Game.GameMsg.Builder getGameMsgBuilder() {
        return getGameMsgFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       */
      @Override
      public Game.GameMsgOrBuilder getGameMsgOrBuilder() {
        if ((typeCase_ == 3) && (gameMsgBuilder_ != null)) {
          return gameMsgBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 3) {
            return (Game.GameMsg) type_;
          }
          return Game.GameMsg.getDefaultInstance();
        }
      }
      /**
       * <pre>
       *  玩法 game
       * </pre>
       *
       * <code>.com.z.model.proto.GameMsg gameMsg = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Game.GameMsg, Game.GameMsg.Builder, Game.GameMsgOrBuilder>
          getGameMsgFieldBuilder() {
        if (gameMsgBuilder_ == null) {
          if (!(typeCase_ == 3)) {
            type_ = Game.GameMsg.getDefaultInstance();
          }
          gameMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Game.GameMsg, Game.GameMsg.Builder, Game.GameMsgOrBuilder>(
                  (Game.GameMsg) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 3;
        onChanged();;
        return gameMsgBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.z.model.proto.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:com.z.model.proto.MyMessage)
    private static final MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyMessage();
    }

    public static MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_z_model_proto_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_z_model_proto_MyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017MyMessage.proto\022\021com.z.model.proto\032\nUs" +
      "er.proto\032\nGame.proto\"}\n\tMyMessage\022\n\n\002id\030" +
      "\001 \001(\005\022-\n\007userMsg\030\002 \001(\0132\032.com.z.model.pro" +
      "to.UserMsgH\000\022-\n\007gameMsg\030\003 \001(\0132\032.com.z.mo" +
      "del.proto.GameMsgH\000B\006\n\004typeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          User.getDescriptor(),
          Game.getDescriptor(),
        });
    internal_static_com_z_model_proto_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_z_model_proto_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_z_model_proto_MyMessage_descriptor,
        new String[] { "Id", "UserMsg", "GameMsg", "Type", });
    User.getDescriptor();
    Game.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
