# es配置
elasticsearch:
  rest:
    clusterName: my_cluster
    clusterNodes: 49.232.226.131 #多个节点地址，用逗号分隔
    clusterPorts: 9200
    connection-timeout: 8000     # 可选，连接超时时间（毫秒）
    read-timeout: 60000          # 可选，读取超时时间（毫秒）
#    management:
#      health:
#        elasticsearch:
#          enabled: true
#          uris: http://49.232.226.131:9200
#          period: 30s

spring:
  data:
    redis:
      # 地址
      host: 8.137.63.141
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      username:
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

