// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common_user.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Z.Model.Proto {

  /// <summary>Holder for reflection information generated from common_user.proto</summary>
  public static partial class CommonUserReflection {

    #region Descriptor
    /// <summary>File descriptor for common_user.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommonUserReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFjb21tb25fdXNlci5wcm90bxIRY29tLnoubW9kZWwucHJvdG8iJQoIVXNl",
            "ckRhdGESCwoDdWlkGAEgASgDEgwKBG5hbWUYAiABKAkqVAoIVXNlclR5cGUS",
            "CgoGQ09NTU9OEAASEAoMTElORV9NQU5BR0VSEAESDQoJTElORV9WSVAxEAIS",
            "DQoJTElORV9WSVAyEAMSDAoHTUFOQUdFUhCQTiorCglFbWFpbFR5cGUSDgoK",
            "RVRfREVGQVVMVBAAEg4KCkVUX1NQRUNJQUwQASobCgVZZXNObxIICgRZTl9O",
            "EAASCAoEWU5fWRABKoUBCghCYW5rVHlwZRIOCgpCVF9ERUZBVUxUEAASDgoK",
            "QlRfREVQT1NJVBABEg8KC0JUX1dJVEhEUkFXEAISDwoLQlRfVFJBTlNGRVIQ",
            "AxIMCghCVF9FTUFJTBAEEhIKDkJUX1JFREVFTV9DT0RFEAUSCQoFQlRfR00Q",
            "ZBIKCgVCVF9BSRDIASpACg9UcmFuc2ZlckxvZ1R5cGUSDgoKVFRfREVGQVVM",
            "VBAAEg8KC1RUX1RSQU5TRkVSEAESDAoIVFRfUkVCRVQQAipsCghHb2xkVHlw",
            "ZRINCglHVF9ERUFVTFQQABIOCgpHVF9ERVBPU0lUEAESDwoLR1RfV0lUSERS",
            "QVcQAhIMCghHVF9FTUFJTBADEgsKB0dUX0dBTUUQBBIJCgVHVF9HTRBkEgoK",
            "BUdUX0FJEMgBKjsKDk1vZGlmeVVzZXJUeXBlEgwKCE1VVF9OQU1FEAASDAoI",
            "TVVUX0lDT04QARINCglNVVRfUEhPTkUQAioyCglDb2RlU3RhdGUSDAoIQ1Nf",
            "Tk9VU0UQABIKCgZDU19VU0UQARILCgdDU19USU1FEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Com.Z.Model.Proto.UserType), typeof(global::Com.Z.Model.Proto.EmailType), typeof(global::Com.Z.Model.Proto.YesNo), typeof(global::Com.Z.Model.Proto.BankType), typeof(global::Com.Z.Model.Proto.TransferLogType), typeof(global::Com.Z.Model.Proto.GoldType), typeof(global::Com.Z.Model.Proto.ModifyUserType), typeof(global::Com.Z.Model.Proto.CodeState), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Z.Model.Proto.UserData), global::Com.Z.Model.Proto.UserData.Parser, new[]{ "Uid", "Name" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///*
  ///用户类型
  /// </summary>
  public enum UserType {
    /// <summary>
    ///普通用户
    /// </summary>
    [pbr::OriginalName("COMMON")] Common = 0,
    /// <summary>
    /// 一级代理（每条线的总控）
    /// </summary>
    [pbr::OriginalName("LINE_MANAGER")] LineManager = 1,
    /// <summary>
    /// 二级代理
    /// </summary>
    [pbr::OriginalName("LINE_VIP1")] LineVip1 = 2,
    /// <summary>
    /// 三级代理
    /// </summary>
    [pbr::OriginalName("LINE_VIP2")] LineVip2 = 3,
    /// <summary>
    ///总控
    /// </summary>
    [pbr::OriginalName("MANAGER")] Manager = 10000,
  }

  public enum EmailType {
    /// <summary>
    ///默认的转账邮件
    /// </summary>
    [pbr::OriginalName("ET_DEFAULT")] EtDefault = 0,
    /// <summary>
    ///特定邮件
    /// </summary>
    [pbr::OriginalName("ET_SPECIAL")] EtSpecial = 1,
  }

  /// <summary>
  ///通用 0，1 状态
  /// </summary>
  public enum YesNo {
    /// <summary>
    ///否
    /// </summary>
    [pbr::OriginalName("YN_N")] YnN = 0,
    /// <summary>
    ///是
    /// </summary>
    [pbr::OriginalName("YN_Y")] YnY = 1,
  }

  /// <summary>
  ///银行金额变动类型
  /// </summary>
  public enum BankType {
    /// <summary>
    ///默认
    /// </summary>
    [pbr::OriginalName("BT_DEFAULT")] BtDefault = 0,
    /// <summary>
    ///存入
    /// </summary>
    [pbr::OriginalName("BT_DEPOSIT")] BtDeposit = 1,
    /// <summary>
    ///取出
    /// </summary>
    [pbr::OriginalName("BT_WITHDRAW")] BtWithdraw = 2,
    /// <summary>
    ///转账
    /// </summary>
    [pbr::OriginalName("BT_TRANSFER")] BtTransfer = 3,
    /// <summary>
    ///邮件
    /// </summary>
    [pbr::OriginalName("BT_EMAIL")] BtEmail = 4,
    /// <summary>
    ///兑换码
    /// </summary>
    [pbr::OriginalName("BT_REDEEM_CODE")] BtRedeemCode = 5,
    /// <summary>
    ///后台
    /// </summary>
    [pbr::OriginalName("BT_GM")] BtGm = 100,
    /// <summary>
    ///自动
    /// </summary>
    [pbr::OriginalName("BT_AI")] BtAi = 200,
  }

  /// <summary>
  ///银行金额变动类型
  /// </summary>
  public enum TransferLogType {
    /// <summary>
    ///默认
    /// </summary>
    [pbr::OriginalName("TT_DEFAULT")] TtDefault = 0,
    /// <summary>
    ///转账
    /// </summary>
    [pbr::OriginalName("TT_TRANSFER")] TtTransfer = 1,
    /// <summary>
    ///返利
    /// </summary>
    [pbr::OriginalName("TT_REBET")] TtRebet = 2,
  }

  /// <summary>
  ///钱包金额变动类型
  /// </summary>
  public enum GoldType {
    /// <summary>
    ///默认
    /// </summary>
    [pbr::OriginalName("GT_DEAULT")] GtDeault = 0,
    /// <summary>
    ///存入
    /// </summary>
    [pbr::OriginalName("GT_DEPOSIT")] GtDeposit = 1,
    /// <summary>
    ///取出
    /// </summary>
    [pbr::OriginalName("GT_WITHDRAW")] GtWithdraw = 2,
    /// <summary>
    ///邮件
    /// </summary>
    [pbr::OriginalName("GT_EMAIL")] GtEmail = 3,
    /// <summary>
    ///游戏
    /// </summary>
    [pbr::OriginalName("GT_GAME")] GtGame = 4,
    /// <summary>
    ///后台
    /// </summary>
    [pbr::OriginalName("GT_GM")] GtGm = 100,
    /// <summary>
    ///自动
    /// </summary>
    [pbr::OriginalName("GT_AI")] GtAi = 200,
  }

  /// <summary>
  ///修改用户信息类型
  /// </summary>
  public enum ModifyUserType {
    /// <summary>
    ///修改名字
    /// </summary>
    [pbr::OriginalName("MUT_NAME")] MutName = 0,
    /// <summary>
    ///修改头像
    /// </summary>
    [pbr::OriginalName("MUT_ICON")] MutIcon = 1,
    /// <summary>
    ///绑定手机号
    /// </summary>
    [pbr::OriginalName("MUT_PHONE")] MutPhone = 2,
  }

  /// <summary>
  ///点卡状态
  /// </summary>
  public enum CodeState {
    /// <summary>
    ///未使用
    /// </summary>
    [pbr::OriginalName("CS_NOUSE")] CsNouse = 0,
    /// <summary>
    ///使用
    /// </summary>
    [pbr::OriginalName("CS_USE")] CsUse = 1,
    /// <summary>
    ///过期
    /// </summary>
    [pbr::OriginalName("CS_TIME")] CsTime = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///*
  /// 公用结构体 --- 用户数据
  /// </summary>
  public sealed partial class UserData : pb::IMessage<UserData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserData> _parser = new pb::MessageParser<UserData>(() => new UserData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Z.Model.Proto.CommonUserReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData(UserData other) : this() {
      uid_ = other.uid_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserData Clone() {
      return new UserData(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private long uid_;
    /// <summary>
    ///用户id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    ///用户名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0L) hash ^= Uid.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Uid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uid != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Uid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserData other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0L) {
        Uid = other.Uid;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uid = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
